### ISSUE TITLE
Bug in 'alloc' ?

### ISSUE THREAD

**Issue by wboeke** [chochain/eforth#1]
Hello,
Something goes wrong in the following code:
```
here .
create val 8 allot
here .
```
The value of the 2nd 'here' should be 8 bigger than the value of the 1st 'here'. But the difference appears to be only 1. Could you have a look at this?
Maybe it's a good idea to give some demo programs illustrating more advanced forth code, like create ... does> ... and array@ ? The provided test programs are nice but rather basic.

**Comment by chochain** [comment]
Hello Mr. Boeke, thank you for taking interest in eForth. 
1. The reason 'here' incremented by 1 is due to the current decision/experiment. Dynamic array is chosen for parameter memory, also stacks and dictionary. See ~/src/ceforth.h for details. This departs from the classic Forths which use memory blocks.
So, 'here' is no more the memory address but an index to the new dictionary entry. Any new colon word, including create, will increment here by just 1. A bad consequence is that I don't know how to do 'dump' now!
2. I took your suggestion and added some demos that illustrate most of the 'basic' features. Please pull my latest check-in and review the Build & Run section (i.e. ~/tests/lessons420.txt)
3. Will work on adding the advanced.

**Comment by wboeke** [comment]
Hello Chochain,
Thanks for the reply. I tried your lessons420 and it works perfectly. However I'm not very smart, so I need a simple example.
Here is a demo for an array:
```
\ forth:
\ : inc cells ;
\ eforth:
: inc 2* ;
create arr 10 inc allot
136 arr !
arr @ .
137 arr 2 inc + !
arr 2 inc + @ .
```
Thus there are 2 inc's, one for standard forth, one for eforth.
The assignment of 136 works okay, but the assignment of 137 to the 2nd array member causes a crash in eforth.
In your example you are using a normal variable. Maybe that is needed in eforth?

**Comment by chochain** [comment]
Ah, dynamic array is at fault again. 
Since it's no more a continuous block of bytes, accessing an array element needs a new word. 
* array@ ( arr i -- ) and 
* array! ( v arr i -- ) are needed now
So, try whether these work
create arr 10 inc allot    \ this gets you 10 elements
see arr                          \ shows you the array with 10 zeros
136 arr !                        \ treat arr as a regular variable (or array with only 1 element)
see arr                          \ shows 136 taking the arr[0]
137 arr 2 array!             \ this should fill the arr[2]
see arr
arr 2 array@                 \ this gets you the arr[2] back
Unfortunately, eForth is still pretty fragile against these memory exception. It crashes. On the other hand, do enjoy if you can. 8-)
Chochain

**Comment by wboeke** [comment]
Thanks, it works!
